RABBIT_MQ_HOST: 127.0.0.1
RABBIT_MQ_UI_PORT: 15672
RABBIT_MQ_PORT: 5672
RABBIT_NODE_NAME: rabbit@rabbit1-101


MIR_ACCOUNT: kenmec
MIR_PASSWORD: kenmec


RABBIT_MQ_USER: kenmec
RABBIT_MQ_PASSWORD: kenmec

MISSION_CONTROL_HOST: 127.0.0.1
MISSION_CONTROL_PORT: 4000

