RABBIT_MQ_HOST_1: 127.0.0.1
RABBIT_MQ_UI_PORT_1: 15672
RABBIT_MQ_PORT_1: 5672
RABBIT_NODE_NAME_1: rabbit@rabbit1-101

RABBIT_MQ_HOST_2: 192.168.1.5
RABBIT_MQ_UI_PORT_2: 15673
RABBIT_MQ_PORT_2: 5673
RABBIT_NODE_NAME_2: rabbit@rabbit2-101

RABBIT_MQ_USER: kenmec
RABBIT_MQ_PASSWORD: kenmec

MISSION_CONTROL_HOST: 127.0.0.1
MISSION_CONTROL_PORT: 4000

MAC: 3C:6D:66:63:CE:7F
AMR_TYPE: fork
