from enum import Enum


class ReturnCode(str, Enum):
    SUCCESS = '0000'
    UNDELIVERABLE = '1111'

    MISSION_CONTINUE_LOGIN_SUCCESS = '3000'
    MISSION_NOT_SYNC_LOGIN_SUCCESS = '3001'
    MISSION_TIMEOUT_LOGIN_SUCCESS = '3002'
    MISSION_NOT_SYNC_LOGIN_SUCCESS_WITH_AMR_SERVICE = '3003'
    MISSION_NOT_SYNC_LOGIN_SUCCESS_WITH_RESET_STATUS_RESEND_MISSION = '3004'
    LOGIN_SUCCESS_UNEXPECTED = '3006'

    FORMAT_ERROR_LOGIN_ERROR = '3441'
    NOT_IN_SYSTEM_LOGIN_ERROR = '3442'

    SHORTEST_PATH_SERVICE_FAILED = '0001'
    IS_ALLOW_SERVICE_FAILED = '0002'
    IS_ARRIVE_ERROR = '0003'
    IS_AWAY_ERROR = '0005'
    REROUTE_PATH_SERVICE_FAILED = '0006'


REGISTER_RETURN_CODE = [
    ReturnCode.SUCCESS,
    ReturnCode.MISSION_CONTINUE_LOGIN_SUCCESS,
    ReturnCode.MISSION_NOT_SYNC_LOGIN_SUCCESS,
    ReturnCode.MISSION_NOT_SYNC_LOGIN_SUCCESS_WITH_RESET_STATUS_RESEND_MISSION,
    ReturnCode.MISSION_NOT_SYNC_LOGIN_SUCCESS_WITH_AMR_SERVICE,
    ReturnCode.LOGIN_SUCCESS_UNEXPECTED,
    ReturnCode.MISSION_TIMEOUT_LOGIN_SUCCESS,
    ReturnCode.FORMAT_ERROR_LOGIN_ERROR,
    ReturnCode.NOT_IN_SYSTEM_LOGIN_ERROR,
]
